sudo: false
language: python
python:
    - "3.7"
install:
    - pip install behave coverage coveralls graphcat Pillow scikit-image
script:
    - coverage run --source imagecat -m behave --tags ~wip
    - coverage report
after_script:
    - coveralls
inotifications:
    webhooks:
        - https://imagecat.zulipchat.com/api/v1/external/travis?api_key=EqUUovnOE5SbnslatW8bkhbzKesYesB6&stream=repo&topic=builds

