sudo: false
language: python
python:
    - "3.7"
addons:
    apt:
        packages:
            - openexr
install:
    - pip install --upgrade behave coverage coveralls graphcat ipython ipywidgets numpy OpenEXR Pillow scikit-image
script:
    - coverage run --source imagecat -m behave --tags ~wip
    - coverage report
after_script:
    - coveralls
inotifications:
    webhooks:
        - https://imagecat.zulipchat.com/api/v1/external/travis?api_key=EqUUovnOE5SbnslatW8bkhbzKesYesB6&stream=repo&topic=builds

