sudo: false
language: python
python:
    - "3.7"

addons:
    apt:
        packages:
            - graphviz
            - openexr
install:
    - pip install --upgrade behave blinker coverage coveralls graphcat ipython ipywidgets mmh3 nbformat numpy OpenEXR Pillow pygraphviz scikit-image
script:
    - coverage run --source imagecat -m behave
    - coverage report
after_script:
    - coveralls

notifications:
    webhooks:
        - https://imagecat.zulipchat.com/api/v1/external/travis?api_key=EqUUovnOE5SbnslatW8bkhbzKesYesB6&stream=repo&topic=builds
