sudo: false
language: python
python:
    - "3.7"
install:
    - pip install behave coverage coveralls graphcat Pillow scikit-image
script:
    - coverage run --source imagecat -m behave
    - coverage report
after_script:
    - coveralls
