name: Regression tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz graphviz-dev openexr
        python -m pip install --upgrade pip
        pip install behave coverage coveralls ipython ipywidgets mmh3 nbformat numpy OpenEXR Pillow pygraphviz scikit-image
        pip install .
    - name: Run tests
      run: |
        coverage run --parallel-mode --source imagecat -m behave
        coverage combine
        coverage report
    - name: Upload coverage to Coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Archive failed tests
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: failed
        path: features/failed
